---
Name: mainsite
After:
  - 'framework/*'
  - 'cms/*'
  - 'silverstripe-rest-api/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteVersion:
  version: 1.0
SSViewer:
  theme: 'default'
Page:
  extensions:
    - OpenGraphExtension
    - TwitterCardExtension
    - SeoObjectExtension
    - SEOExtension
SiteConfig:
  extensions:
    - CustomSiteConfig
    - OpenGraphExtension
    - TwitterCardExtension
Page_Controller:
  extensions:
    - PageControllerDecorator
ModelAdmin:
  extensions:
    - ModelAdminExtension

SeoConfig:
    Page: true
    ErrorPage: false
    RedirectorPage: false
    VirtualPage: false

APICache:
  CacheLength:
    '604800': '7 Days'
    '518400': '6 Days'
    '432000': '5 Days'
    '345600': '4 Days'
    '259200': '3 Days'
    '172800': '2 Days'
    '86400': '1 Day'
    '43200': '12 hours'
    '21600': '6 hours'
    '10800': '3 hours'
    '7200': '2 hours'
    '3600': '1 hour'
    '1800': '30 minutes'
    '900': '15 minutes'
    '600': '10 minutes'
    '300': '5 minutes'
    '60': '1 minute'

#
# API Authentication
#
# Injector:
#   Authenticator:
#     class: SaltedHerringTokenAuth
#   ApiMemberAuthenticator:
#     class: MemberAuthenticator
#   SessionValidator:
#     class: SessionValidator
#   PermissionChecks:
#     class: SilverstripePermission
# SaltedHerringTokenAuth:
#   DevToken: foobarbaz
# DataController:
#   CORSOrigin: '*'
#   CORSMethods: 'GET, PUT, POST, DELETE, OPTIONS'
#   CORSMaxAge: '1000'
#   CORSAllowHeaders: 'Content-Type, Authorization, X-Requested-With'
#   Owner: Member

App:
  ApiEndpoint: "api/v/1/app/"
SiteApp:
  ApiEndpoint: "api/v/1/siteapp/"
  AdditionalData:
    - SelectValueField: OptionValueField