---
Name: custom_fields
After:
  - 'framework/*'
  - 'cms/*'
---
CustomField:
  Types:
    - BooleanValueField: "boolean"
    - DateValueField: "date"
    - DatetimeValueField: "datetime"
    - DecimalValueField: "decimal"
    - GMapsValueField: "google map"
    - GeolocationField: "geometry"
    - HTMLTextValueField: "html text"
    - HTMLTextAreaValueField: "html text area"
    - IntValueField: "integer"
    - SelectValueField: "select"
    - TextValueField: "text"
    - TextAreaValueField: "text area"
  ApiEndpoint: "api/v/1/data/"
  AdditionalData:
    - SelectValueField: OptionValueField
CustomForm:
  ApiEndpoint: "api/v/1/data/"